class_niveau:
    resource: "@ClassBundle/Resources/config/routing/niveau.yml"
    prefix:   /niveau
class_classe:
    resource: "@ClassBundle/Resources/config/routing/classe.yml"
    prefix:   /classe
class_elevesclasse:
    resource: "@ClassBundle/Resources/config/routing/elevesclasse.yml"
    prefix:   /elevesclasse
class_profclass:
    resource: "@ClassBundle/Resources/config/routing/profclass.yml"
    prefix:   /profclass
class_reclamation:
    resource: "@ClassBundle/Resources/config/routing/reclamation.yml"
    prefix:   /reclamation
