<?php

namespace ServiceBundle\Repository;

/**
 * servicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class servicesRepository extends \Doctrine\ORM\EntityRepository
{
}
